### ISSUE TITLE
User is getting "The Files could not be loaded. java.lang.IllegalArgumentException: Task size too large" when they try to upload.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/local-storage-module#109]
### What is the expected behavior?
users should be able to upload files to storage.

### What is the actual behavior?
User has a specific folder that is giving them the error "The Files could not be loaded. java.lang.IllegalArgumentException: Task size too large" when they try to upload.

### What steps can be taken to replicate the problem?
We cannot recreate this, but for the user it is quite simple.

**Comment by tejohnso** [comment]
@robb-price I'll close this for now - go ahead and re-open if necessary.
